# Generated by Django 5.1.10 on 2026-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_shop_id_44685a_idx',
            old_name='products_pr_shop_id_7c1a47_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_categor_14b9c0_idx',
            old_name='products_pr_categor_78da86_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_fec1f9_idx',
            old_name='products_pr_is_acti_0ae3a3_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_created_52f0d7_idx',
            old_name='products_pr_created_21087c_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_product_78e37c_idx',
            old_name='products_pr_product_384543_idx',
        ),
    ]
