# Generated by Django 5.1.10 on 2026-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='cart_order_shop_id_73c467_idx',
            old_name='cart_order_shop_id_8144ce_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='cart_order_custome_3e7638_idx',
            old_name='cart_order_custome_2862c7_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='cart_order_order_n_bd9406_idx',
            old_name='cart_order_order_n_19710d_idx',
        ),
        migrations.RenameIndex(
            model_name='ordergroup',
            new_name='cart_orderg_custome_e73501_idx',
            old_name='cart_orderg_custome_55d017_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='cart_orderi_order_i_c38a6b_idx',
            old_name='cart_orderi_order_i_1ced7e_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='cart_orderi_product_edba2f_idx',
            old_name='cart_orderi_product_9b0897_idx',
        ),
    ]
