# Generated by Django 5.1.10 on 2026-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_postgis_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shop',
            new_name='shops_shop_city_0942b1_idx',
            old_name='shops_shop_city_42c03f_idx',
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='shops_shop_pincode_a20a2a_idx',
            old_name='shops_shop_pincode_aa694f_idx',
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='shops_shop_is_acti_df091f_idx',
            old_name='shops_shop_is_acti_144de7_idx',
        ),
        migrations.RenameIndex(
            model_name='shop',
            new_name='shops_shop_owner_i_de9788_idx',
            old_name='shops_shop_owner_i_40e136_idx',
        ),
        migrations.RenameIndex(
            model_name='shopcategory',
            new_name='shops_shopc_slug_287766_idx',
            old_name='shops_shopc_slug_c48daa_idx',
        ),
        migrations.RenameIndex(
            model_name='shopcategory',
            new_name='shops_shopc_sort_or_351cfb_idx',
            old_name='shops_shopc_sort_or_034e6b_idx',
        ),
    ]
