# Generated by Django 5.1.10 on 2026-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productreview',
            new_name='reviews_pro_product_88eae8_idx',
            old_name='reviews_pro_product_b78c02_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='reviews_pro_user_id_3d1523_idx',
            old_name='reviews_pro_user_id_d68447_idx',
        ),
        migrations.RenameIndex(
            model_name='shopreview',
            new_name='reviews_sho_shop_id_de5a27_idx',
            old_name='reviews_sho_shop_id_328610_idx',
        ),
        migrations.RenameIndex(
            model_name='shopreview',
            new_name='reviews_sho_user_id_2217ec_idx',
            old_name='reviews_sho_user_id_ce72ad_idx',
        ),
    ]
